### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by rm-code**
Picked a better translation for "refresh" and fixed a small typo in the
translation of "remote console".

### CODE REVIEW

**Comment by pkulchenko** [comment]
Robert, thank you for the update!

**Comment by rm-code** [comment]
My pleasure!

**Comment by riidom** [comment]
Thanks for helping out, I am out of the coding loop for a few months, greatly appreciated!

**Comment by pkulchenko** [comment]
Thanks to both of you for keeping the translation up-to-date! I'll update #70 when I get the changes for #416 merged as there were several changes for the find/replace messages.

**Comment by rm-code** [comment]
@pkulchenko 
I just noticed there is one line which hasn't gotten translated yet:
```Lua
["Mapped remote request for '%s' to '%s'."] = "Mapped remote request for '%s' to '%s'."
```
@riidom What do you think about this translation?
```Lua
["Mapped remote request for '%s' to '%s'."] = "Fern-Aufforderung für '%s' auf '%s' abgebildet."
```

**Comment by pkulchenko** [comment]
I can update it if you agree on the spelling ;)

**Comment by riidom** [comment]
Yes, is good I think.

**Pull request merged**
