### PR TITLE
Added config option for transparency of window.

### PR DESCRIPTION
**Pull request by paul-reilly**
Just a quick addition for a substantially increased zen quotient. :)

### CODE REVIEW

**Comment by pkulchenko** [comment]
@paul-reilly, interesting! Can you squash the two commits? ;)

**Comment by madmaxoft** [comment]
@pkulchenko Github already supports squash-merge for PRs, use the dropdown next to the Merge button :)

**Comment by pkulchenko** [comment]
Good; I can also always squash it manually, but would prefer to get PRs in mergeable state ;).

**Comment by paul-reilly** [comment]
Closed, made new one #873.

**Pull request closed without merging**
