### PR TITLE
Update moai API to community version 1.8 RC

### PR DESCRIPTION
**Pull request by feserr**

### CODE REVIEW

**Comment by pkulchenko** [comment]
@feserr, the pull request looks good, but some of the `args` values don't have parens for them. Is that intentional or something that can be fixed?

**Comment by feserr** [comment]
I did not realize about that, I use the last version of the master branch of the exporter. The exporter throw some error that I were not error and I comment the lines of the code that throw it.

I do not think that this is the cause of the problem, but I will fix the exporter to fix this problem.

**Comment by feserr** [comment]
I have see that the old version also have args without parens, it happens when the arguments are only one. Also I have see that some of the returns of the new version are wrong, I will try to fix it.

**Comment by pkulchenko** [comment]
@feserr, if you don't plan to get to it soon, I can merge as is as it's at least not worse than what we have now and you can submit an update when you get a chance to fix it.

**Comment by feserr** [comment]
Sorry, but I have been finishing a master degree and now I am doing the master degree final project.
You can merge it and I will fix it when i finish what I am doing.

**Comment by pkulchenko** [comment]
@feserr, sounds good; merged. Thanks!

**Pull request closed without merging**
