### PR TITLE
Added a Lua API and auto-complete description for OpenRA

### PR DESCRIPTION
**Pull request by Mailaender**
@OpenRA is a real-time strategy game engine with Lua https://github.com/OpenRA/OpenRA/wiki/Map-Scripting. This adds an automatically generated Lua API definition for it's latest release. Code completion and tooltips work. More than any other IDE to my knowledge currently offers.

There is a specialty that all game actors in a `map.yaml` file in the same folder of the *.lua script get automatically converted to global variables by the Lua binding in game so <kbd>Analyze</kbd> will spit out a lot of warnings, but it is already very useable.

### CODE REVIEW

**Comment by pkulchenko** [comment]
@Mailaender, thank you for the patch. This should be submitted as a [package](https://github.com/pkulchenko/ZeroBranePackage/). Look at [urho3d](https://github.com/pkulchenko/ZeroBranePackage/blob/master/urho3d.lua) for a close example of how API and Interpreter are registered in a plugin.

**Comment by Mailaender** [comment]
Submitted https://github.com/pkulchenko/ZeroBranePackage/pull/37 which also makes it easier to redistribute.

**Comment by Mailaender** [comment]
What steps are necessary to add live debugging support? Is it even possible in a sandboxed environment?

**Comment by pkulchenko** [comment]
> What steps are necessary to add live debugging support? Is it even possible in a sandboxed environment?

You need to add `scratchextloop` property to your interpreter. `false` value means that the entire application will be aborted and restarted, `true` means that the code in the current page will be stopped, reloaded and continued. `true` usually works well with games/environments that have processing/drawing callbacks; `false` works for cases when the entire application needs to be restarted when the changes are made (like you would have with a standalone Lua script that doesn't have event loop).

I'd start with `scratchextloop = true` and see if it works (keep in mind that only the current file is going to be reloaded); you can look at the existing interpreters to see how it's specified.

**Pull request closed without merging**
