### PR TITLE
Add support for `fold.compact` flag by lpeg lexer.

### PR DESCRIPTION
**Pull request by moteus**
See also #847

### CODE REVIEW

**Comment by pkulchenko** [comment]
@moteus, why did you add `editor:SetProperty("fold.line.comments", "1")` to the default Lua lexer? I don't think it's supported there...

**Comment by moteus** [comment]
ZBS calls both code parts for editor with such lexer. May be it is bug and should be fixed.
Agree. This value can be set only once if scintilla does not reset this value somehow.
But I make it just in case.

**Comment by pkulchenko** [comment]
It does look strange that it's in two places, but I think it's the result of some of the settings being set *after* the lexer is selected (but before it's used), but in the case of lexlpeg it needs to be set *before* the lexer is selected, so it ended up in two places. The second group of calls gets ignored for lexlpeg lexers, but it's still needed for the default (Scintilla) lexers.

There is a related comment in editor.lua:

> need to set folding property after lexer is set, otherwise the folds are not shown (wxwidgets 2.9.5)

I can probably consolidate it into one function and just call it in two places; I'll think about it.

**Comment by moteus** [comment]
>but in the case of lexlpeg it needs to be set before the lexer is selected 

In fact no.
lpeglexer asks parameters when it needs it. In this case when calls `fold` callback. (`M.property_int[....]` calls `editor:GetProperty` each time)
And in my tests I saw that first values really do not count at all because they overwrites in second place.

**Comment by pkulchenko** [comment]
@moteus, merged; thank you for the patch!

**Pull request closed without merging**
