### PR TITLE
Integrate changes from Marmalade 7.7-7.9

### PR DESCRIPTION
**Pull request by nickchops**
- Update Marmalade API reference for autocomplete to match Marmalade 7.8/7.9.
- Marmalade interpreter updates to allow: ZeroBrane to pick up debug/release settings live from Marmalade Hub; Hub to open projects in ZeroBrane, auto-setting the interpreter and displaying the full project folder.

### CODE REVIEW

**Comment by pkulchenko** [comment]
Nick, looks good, except the `settings.lua` change. As I said earlier, you don't need this setting and I'd prefer to do it in some other way. For example, something like this should work when launching ZBS from Marmalade Hub:

```
zbstudio.exe <marmalade project> -cfg "interpreter='marmalade'"
```

This will set the project to `<marmalade project>` (if it's an existing folder) and select `marmalade` as its interpreter (if it's a new project).

Also, it may be better to use branches for pull requests as it allows me to modify the commits in those requests without your messing your master branch. You can "fix" the commits and "force push" them to your repo, which should update the pull request.

**Comment by nickchops** [comment]
OK, will check how we're launching and try that out. I assume the -cfg flag
will overwrite any other way the interpreter is set (e.g. in user config
file).

Will branch for the next request and leave this as master if that's OK.

Nick

**Comment by nickchops** [comment]
Oh, actually changing the zbstudio.exe call will need the Hub updating in
our SDK, which obviously won't go public until we have a release. I'll
check if it makes sense to have any of those changes in without the
interpreter being set. If not, I guess we hold out the pull until our next
release.

**Comment by pkulchenko** [comment]
> I assume the -cfg flag will overwrite any other way the interpreter is set (e.g. in user config file).

Yes, but only for "new" projects that don't have the interpreter set yet, which is what you want in this case anyway.

> Will branch for the next request and leave this as master if that's OK.

Sure; you can just update and "force push" to your current master.

> I'll check if it makes sense to have any of those changes in without the interpreter being set. If not, I guess we hold out the pull until our next release.

I can't say for sure, but without the interpreter being set, your users can still set it manually. Also, don't forget that ZBS will use the "current" interpreter for new projects, which is likely to be "marmalade" for Marmalade users anyway. The logic works like this: when a new project is opened, the IDE is either using "interpreter" value or is using the current interpreter set (for the project that is currently open). If none are specified, the default "lua" interpreter is used.

**Comment by nickchops** [comment]
Can you clarify what you mean by "new projects"... since ZB doesnt actually
have a project format and you just set from a directory, I'm not sure what
that means. Although, I guess it saves data somewhere as it remembers open
docs etc per project.

Will take me a while to download Qt and rebuild the SDK side so will update
later.

**Comment by pkulchenko** [comment]
> Although, I guess it saves data somewhere as it remembers open docs etc per project.

Right; it saves some data about the configuration of your open files and the selected interpreter per directory (per project in ZBS terminology). When a new directory/project is selected (either from the GUI or by providing a directory as a parameter), the interpreter is selected based on the logic I described earlier and that selection is saved (and can be changed manually).

**Comment by nickchops** [comment]
Seems to be working well. Not sure why the engineer didnt want to jut use
the "interpreter" config in hindsight!

**Comment by pkulchenko** [comment]
> Seems to be working well.

So, you don't need the change in the `settings.lua` file, right?

> Not sure why the engineer didnt want to jut use the "interpreter" config in hindsight!

Probably because it was only recently made to work this way ;). The setting was there for a long time, but it turned out that it wasn't working as I intended, so I fixed it. I'll make sure it's reflected in the documentation.

**Comment by nickchops** [comment]
Cool. I did think I'd tried to get "interpreter=" and failed before. I've force pushed the settings.lua change out of the request (naughty, but you asked for it!)

**Pull request merged**
