### PR TITLE
Feature/autocomplete fixes

### PR DESCRIPTION
**Pull request by halfnelson**
Came across these problems when trying to get autocomplete to use my autogenerated API definitions.
- Inheritance wasn't being walked when resolving an assign
- a variable that was named the same as the start of another variable would not get its assign resolved
- changed a test to fail  which was previously passing due to behaviour of above bug.

### CODE REVIEW

**Comment by pkulchenko** [comment]
@halfnelson, thank you for the patch! I think the changes look good, but I'll review more carefully in few days (traveling atm).

As for the test, as far as I understand you thought it was wrong, so you updated it to fail and then fixed with your other commit?

**Comment by pkulchenko** [comment]
Actually, the test still fails, so I guess the underlying issue still needs to be fixed.

**Comment by halfnelson** [comment]
yeah, the test still fails, i fixed the issue that made it pass when it
probably shouldn't have. Not sure how to fix and I wanted to get these
submitted.

**Comment by pkulchenko** [comment]
@halfnelson, pushed your changes with a bit of clean-up to autocomp-inheritance-in-assignment branch. All the tests are passing; take a look if these changes are working for you.

**Pull request closed without merging**
